# AppVeyor build configuration
# https://www.appveyor.com/docs/build-configuration

os: Visual Studio 2015

build: false # use custom build_script instead

environment:
  matrix:
    - tbs_platform: "Win32"
      tbs_config: "AnalysisRelease"

    - tbs_platform: "x64"
      tbs_config: "AnalysisRelease"

    - tbs_platform: "Win32"
      tbs_config: "Release"

    - tbs_platform: "x64"
      tbs_config: "Release"

    - tbs_platform: "Win32"
      tbs_config: "Debug"

    - tbs_platform: "x64"
      tbs_config: "Debug"

install:
  - ps: if($env:tbs_platform -eq 'x64') { $env:vcvar_arg = 'x86_amd64'; } else { $env:vcvar_arg = 'x86'; }
  - ps: if($env:tbs_platform -eq 'x64') { $env:ms_build_suffix = 'Bin\amd64'; } else { $env:ms_build_suffix = 'Bin'; }
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" %vcvar_arg%'
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%vcvar_arg%'
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\%ms_build_suffix%;%PATH%

before_build:
  #packages from nuget
  - nuget restore mandelbulber2.sln
 
build_script:
  - msbuild mandelbulber2.sln /p:Configuration=%tbs_config% /p:Platform=%tbs_platform%
  - netstat -ab
  - tree /F
  
after_build:
  # zip the archive
  - 7z a mandelbulber-%tbs_config%-%tbs_platform%.zip build-win\%tbs_config%\%tbs_platform%
  
#specify artifacts to upload
artifacts:
  - path: mandelbulber-%tbs_config%-%tbs_platform%.zip
    name: Mandelbulber-%tbs_config%-%tbs_platform%

#deploy:
# todo, see here for instructions: https://www.appveyor.com/docs/deployment/github

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/093389bb43bd353724ae
  - provider: Email
    to:
      - buddhi1980@gmail.com
      - sebastian.jennen@gmx.de
