build:
  image: acidhunter/mandelbulber2-docker:trusty
  before_script:
#     - eval $(ssh-agent -s)
#     - ssh-add <(echo "$SSH_PRIVATE_KEY")
#     - mkdir -p ~/.ssh
#     - echo "${SSH_PRIVATE_KEY}" > id_rsa
#     - chmod 600 id_rsa
#     - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
#     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - QTDIR="/opt/qt57"
    - PATH="$QTDIR/bin:$PATH"
    - mkdir mandelbulber2/build
    - cd mandelbulber2/build
    - qmake ../qmake/mandelbulber.pro
    - make -j4
    - tree .
    - cp -vurL "../deploy/share" "usr/"
  artifacts:
     untracked: true
     paths:
      - mandelbulber2/build/
     expire_in: 1 week
  only:
    - npanic
  tags:
    - mandelbulber
