# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/

language: cpp

os:
  - linux
  - osx

env:
  matrix:
    - CONFIG=release

install:
 # qt5-default libqt5gui5
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt56
      && sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386
      && sudo apt-get install -y qt56base qt56tools
      && sudo apt-get install -y libpng12-0 libpng12-dev libgsl0-dev libgsl0ldbl libgomp1
      && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
      && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
      && lsb_release -a
      ;
    else
         brew update > /dev/null
      && brew install qt5 gsl
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
#build
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt56"
      && PATH="$QTDIR/bin:$PATH"
      && qt56-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd mandelbulber2/Release
  - qmake mandelbulber.pro
	- make -j3

# testing
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo ln -s `pwd`/../deploy/share/mandelbulber2 /usr/share/mandelbulber2
      && ./mandelbulber2 --test
    else
         echo 'TODO test...'
      ;
    fi

notifications:
  email:
    - buddhi1980@gmail.com
    - sebastian.jennen@gmx.de
  webhooks:
    - https://webhooks.gitter.im/e/045502f8fca741c11771
